{{ if .Values.deploySecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "chart.fullname" . }}-secret
type: Opaque
data:
  ConnectionStrings__DefaultConnection: {{ required "ConnectionStrings.DefaultConnection must be defined!" .Values.ConnectionStrings.DefaultConnection | b64enc | quote }}
  AuthenticationOptions__PublicSigningKey: {{ required "AuthenticationOptions.PublicSigningKey must be defined!" .Values.AuthenticationOptions.PublicSigningKey | b64enc | quote }}
  AuthenticationOptions__PrivateSigningKey: {{ required "AuthenticationOptions.PrivateSigningKey must be defined!" .Values.AuthenticationOptions.PrivateSigningKey | b64enc | quote }}
  MailOptions__SenderMailAddress: {{ required "MailOptions.SenderMailAddress must be defined!" .Values.MailOptions.SenderMailAddress | b64enc | quote }}
  MailOptions__SenderMailPassword: {{ required "MailOptions.SenderMailPassword must be defined!" .Values.MailOptions.SenderMailPassword | b64enc | quote }}
{{ end }}
