version: "3.8"
networks:
  salaryservice-deb:
    driver: bridge


services:
  db-debug:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Employees
    ports:
      - 5432:5432
    networks:
      - salaryservice-deb

  salary-service-api:
    depends_on:
      - "db-debug"
    build: 
      dockerfile: SalaryService.Api/Dockerfile
      context: .
    ports:
      - 5000:80
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - LOGS_PATH=/var/log/wb-auth
      - DefaultConnection="Host=db-debug;port=5432;Database=Employees;Username=postgres;Password=postgres"
    volumes:
      - ./logs/wb-auth:/var/log/wb-analytics-api
    networks:
      - salaryservice-deb
    
    