version: "3.8"
networks:
  salaryservice-deb:
    driver: bridge


services:
  db-debug:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: InnerCircleFinanceDb
    ports:
      - 5433:5432
    networks:
      - salaryservice-deb

  salary-service-api:
    depends_on:
      - "db-debug"
    build: 
      dockerfile: SalaryService.Api/Dockerfile
      context: .
    ports:
      - 5000:80
    environment: 
      - ASPNETCORE_ENVIRONMENT=Debug
      - LOGS_PATH=/var/log/salary-service-api
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=postgres;Host=db-debug;port=5432;Database=InnerCircleFinanceDb
    volumes:
      - ./logs/wb-auth:/var/log/salary-service-api
    networks:
      - salaryservice-deb
    
    