  name: deploy service to dev k8s

  on:
    push:
      branches:
        - develop

      tags:
        - v*

    pull_request:

  env:
    GUTHUB_REGISTRY: ghcr.io

  jobs:
    deploy-to-dev-k8s:
      name: Deploy service to k8s for development environment
      if: github.event_name == 'push'
      runs-on: ubuntu-18.04

      steps:
        - name: checkout 
          uses: actions/checkout@v1
        - name: Build and push image
          run: |
              docker login ${{ env.GUTHUB_REGISTRY }} -u ${{ github.actor }} -p ${{ secrets.GH_REGISTRY_TOKEN }}
              docker build -t $GUTHUB_REGISTRY/tourmalinecore/inner-circle/dev-salary-service:latest -t $GUTHUB_REGISTRY/tourmalinecore/inner-circle/dev-salary-service:${{ github.sha }} -f SalaryService.Api/Dockerfile .
              docker push $GUTHUB_REGISTRY/tourmalinecore/inner-circle/dev-salary-service:latest
              docker push $GUTHUB_REGISTRY/tourmalinecore/inner-circle/dev-salary-service:${{ github.sha }}
        - name: Deploy
          uses: WyriHaximus/github-action-helm3@v2
          with:
            exec: helm upgrade --namespace dev-inner-circle --create-namespace --install dev-salary-service-api 
                    --set "aspnetcoreEnvironment=Development"
                    --set "ingress.host"=${{ secrets.DEV_HOST }}
                    --set "deployment.appsettings.ConnectionStrings.DefaultConnection=${{ secrets.DEV_POSTGRESQLCONNECTIONSTRING }}"
                    --set "imageCredentials.username=${{ github.actor }}" 
                    --set "imageCredentials.password=${{ secrets.GH_REGISTRY_TOKEN }}" 
                    --set "image.tag=${{ github.sha }}"
                    --set "image.pullPolicy=Always"
                    ./InnerCircle.SalaryService/ci/chart
            kubeconfig: '${{ secrets.DEV_KUBECONFIG }}'